language: go
go:
  - 1.9
script:
  - go get bitbucket.org/tmedwards/tweego
  - make
deploy:
  provider: pages
  local_dir: build
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  on:
    branch: master
before_deploy:
  - openssl aes-256-cbc -K $encrypted_9c3f5c915ae6_key -iv $encrypted_9c3f5c915ae6_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
addons:
  ssh_known_hosts:
    - buttplug.world
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --quiet --delete-after build/* buttplugworld@buttplug.world:/home/buttplugworld/beta.buttplug.world/tutorial
  on:
    branch: master
