language: go
go:
  - 1.9
script:
  - go get bitbucket.org/tmedwards/tweego
  - make
deploy:
  - provider: pages
    skip-cleanup: true
    local-dir: build
    github-token: $GITHUB_TOKEN
    on:
      branch: master
