language: go
go:
  - 1.9
script:
  - go get bitbucket.org/tmedwards/tweego
  - make
before_deploy:
  - openssl aes-256-cbc -K $encrypted_9c3f5c915ae6_key -iv $encrypted_9c3f5c915ae6_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
addons:
  ssh_known_hosts:
    - buttplug.world
deploy:
  - provider: script
    skip-cleanup: true
    script: rsync -r --quiet --delete-after build/* buttplugworld@buttplug.world:/home/buttplugworld/buttplug.world/tutorial
    on:
      branch: release
  - provider: script
    skip-cleanup: true
    script: rsync -r --quiet --delete-after build/* buttplugworld@buttplug.world:/home/buttplugworld/beta.buttplug.world/tutorial
    on:
      branch: beta
  - provider: pages
    skip-cleanup: true
    local-dir: build
    github-token: $GITHUB_TOKEN
    on:
      branch: master
